import { XMLParser } from 'fast-xml-parser';
const RESEARCH='https://www.curecancerwithai.com/api/v1/research';
const ESEARCH='https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi';
const EFETCH='https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi';
const UA='CancerInsight/5.0 educational-research-project';
export const norm=s=>(s||'').trim().toLowerCase().replace(/[_-]/g,' ').replace(/\s+/g,' ');
export const display=s=>norm(s).replace(/\b\w/g,c=>c.toUpperCase());
const arr=x=>x==null?[]:Array.isArray(x)?x:[x];
const text=x=>typeof x==='string'?x:x?.['#text']||'';
export function treatmentValues(v){return arr(v).flatMap(x=>String(x||'').split(/[,;|]/)).map(norm).filter(Boolean)}
function paperNorm(p){return {...p,treatmentTypes:treatmentValues(p.treatmentTypes),publication_types:arr(p.publication_types),pubmedId:String(p.pubmedId||p.pmid||'')}}
function parseArticle(a){const mc=a?.MedlineCitation||{}, art=mc.Article||{}, journal=art.Journal||{}; const pmid=text(mc.PMID)||String(mc.PMID||''); const abst=arr(art.Abstract?.AbstractText).map(text).filter(Boolean).join('\n'); const authors=arr(art.AuthorList?.Author).map(x=>[x.ForeName,x.LastName].filter(Boolean).join(' ')).filter(Boolean); const pt=arr(art.PublicationTypeList?.PublicationType).map(text).filter(Boolean); const ids=arr(a?.PubmedData?.ArticleIdList?.ArticleId); const doi=ids.find(x=>x?.['@_IdType']==='doi'); const pmc=ids.find(x=>x?.['@_IdType']==='pmc'); const date=journal.JournalIssue?.PubDate||{}; const ds=[date.Year,date.Month,date.Day].filter(Boolean).join(' '); return {pubmedId:pmid,pubmed_title:text(art.ArticleTitle),pubmed_abstract:abst,pubmed_journal:text(journal.Title)||text(journal.ISOAbbreviation),pubmed_date:ds,pubmed_authors:authors.join(', '),publication_types:pt,doi:text(doi),pmc_id:text(pmc),pubmed_url:pmid?`https://pubmed.ncbi.nlm.nih.gov/${pmid}/`:'',pmc_url:text(pmc)?`https://pmc.ncbi.nlm.nih.gov/articles/${text(pmc)}/`:''};}
async function pubmedByIds(ids){if(!ids.length)return{}; const r=await fetch(EFETCH+'?db=pubmed&retmode=xml&id='+encodeURIComponent(ids.join(',')),{headers:{'User-Agent':UA}}); if(!r.ok)return{}; const xml=await r.text(); const j=new XMLParser({ignoreAttributes:false,trimValues:true}).parse(xml); const arts=arr(j?.PubmedArticleSet?.PubmedArticle); return Object.fromEntries(arts.map(parseArticle).filter(x=>x.pubmedId).map(x=>[x.pubmedId,x]));}
export async function searchCancer(input){const cancer=norm(input); if(!cancer)throw Error('Enter a cancer type to search.'); const key=process.env.CANCER_RESEARCH_API_KEY; if(!key)throw Error('The research API key has not been configured.'); const r=await fetch(RESEARCH+'?cancerType='+encodeURIComponent(cancer),{headers:{Authorization:`Bearer ${key}`,'User-Agent':UA},cache:'no-store'}); if(!r.ok)throw Error('The research service could not be reached right now.'); const payload=await r.json(); let papers=arr(payload.data).map(paperNorm); if(!papers.length)throw Error('No research papers were found for that search.'); const meta=await pubmedByIds([...new Set(papers.map(p=>p.pubmedId).filter(Boolean))]); papers=papers.map(p=>({...p,...(meta[p.pubmedId]||{})})).slice(0,20); return buildResult(cancer,papers);}
export function buildResult(cancer,papers){const counts={}; papers.forEach(p=>treatmentValues(p.treatmentTypes).forEach(t=>counts[t]=(counts[t]||0)+1)); const treatments=Object.entries(counts).sort((a,b)=>b[1]-a[1]); return {cancer,papers,treatments,profile:profile(papers)};}
export function profile(papers){const years={},journals={}; let free=0,trials=0,reviews=0,meta=0; papers.forEach(p=>{if(p.pmc_id)free++; const y=(String(p.pubmed_date||p.publicationDate||'').match(/\b(19|20)\d{2}\b/)||[])[0]; if(y)years[y]=(years[y]||0)+1; const j=p.pubmed_journal||p.journal;if(j)journals[j]=(journals[j]||0)+1; const pts=arr(p.publication_types).join(' ').toLowerCase(); if(pts.includes('clinical trial'))trials++;if(pts.includes('review'))reviews++;if(pts.includes('meta-analysis'))meta++;}); const ys=Object.keys(years).map(Number); return {paper_count:papers.length,free_full_text_count:free,latest_year:ys.length?Math.max(...ys):null,journals:Object.keys(journals),clinical_trials:trials,reviews,meta_analyses:meta,year_counts:years,top_journals:Object.entries(journals).sort((a,b)=>b[1]-a[1]).slice(0,10)};}
export async function treatmentEvidence(cancer,treatment,limit=14){const q=`(${norm(cancer)} cancer[Title/Abstract]) AND (${norm(treatment)}[Title/Abstract])`; const s=await fetch(ESEARCH+'?db=pubmed&retmode=json&retmax='+limit+'&term='+encodeURIComponent(q),{headers:{'User-Agent':UA},cache:'no-store'}); if(!s.ok)return[]; const sj=await s.json(); const ids=sj?.esearchresult?.idlist||[]; const m=await pubmedByIds(ids); return ids.map(id=>paperNorm(m[id]||{})).filter(p=>p.pubmedId);}
